name: Playwright E2E Tests (Chromium Only)

on:
  push:
    branches: [ main, master ]
    paths:
      - 'web/**'
      - '.github/workflows/playwright-chromium.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'web/**'
      - '.github/workflows/playwright-chromium.yml'

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
        
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
        
      - name: Install dependencies
        working-directory: ./web
        run: pnpm install --frozen-lockfile
        
      - name: Install Playwright Chromium
        working-directory: ./web
        run: pnpm exec playwright install --with-deps chromium
        
      - name: Run Playwright tests (Chromium)
        working-directory: ./web
        run: pnpm exec playwright test --project=chromium
        env:
          CI: true
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-chromium-${{ github.run_id }}
          path: web/playwright-report/
          retention-days: 30
          
      - name: Upload test traces
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-traces-chromium-${{ github.run_id }}
          path: web/test-results/
          retention-days: 7
